USE stu0714;
DROP TABLE IF EXISTS players;
CREATE TABLE players(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50), number INT, position VARCHAR(10), joined INT, nationality VARCHAR(50));
INSERT INTO players(name, number, position, joined, nationality) VALUES('Ederson', 31, 'GK', 2017, 'Brazil');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Carson', 33, 'GK', 2019, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Walker', 2, 'DF', 2017, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Dias', 3, 'DF', 2020, 'Portugal');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Stones', 5, 'DF', 2016, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Ake', 6, 'DF', 2020, 'Netherlands');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Cancelo', 7, 'DF', 2019, 'Portugal');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Zinchenko', 11, 'DF', 2016, 'Ukraine');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Laporte', 14, 'DF', 2018, 'Spain');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Phillips', 4, 'MF', 2022, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Gundogan', 8, 'MF', 2016, 'Germany');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Grealish', 10, 'MF', 2021, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Rodrigo', 16, 'MF', 2019, 'Spain');
INSERT INTO players(name, number, position, joined, nationality) VALUES('DeBruyne', 17, 'MF', 2015, 'Belgium');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Silva', 20, 'MF', 2017, 'Portugal');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Foden', 47, 'MF', 2016, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Palmer', 80, 'MF', 2018, 'England');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Haaland', 9, 'FW', 2022, 'Norway');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Alvarez', 19, 'FW', 2022, 'Argentina');
INSERT INTO players(name, number, position, joined, nationality) VALUES('Mahrez', 26, 'FW', 2018, 'Algeria');
